// Add new projects here. Case-study copy is a first draft for Slimzy to review.
// No client quotes, performance figures or unverified project timelines are used.
const projects = [
 {id:'zidi',title:'Zidi AI Assistant',category:'video',type:'Explainer video',cover:'assets/zidi-ai-assistant-poster.jpg',video:'assets/zidi-ai-assistant.mp4',intro:'A clear, engaging product story that makes the Zidi AI experience easy to understand.',overview:'An explainer introducing Zidi AI Assistant through a focused product story. The film centres on making an unfamiliar digital experience easier to follow.',focus:'Clarity is the starting point: give each idea space, keep the visual hierarchy clear and use motion to guide attention through the product.',format:'Product explainer / Motion graphics'},
 {id:'axentra',title:'Axentra',category:'video',type:'Product promo video',cover:'assets/axentra-poster.jpg',video:'assets/axentra.mp4',intro:'A product promo bringing the Axentra trading platform to life through interface motion and focused visual pacing.',overview:'A promotional film built around the Axentra product experience. Interface details and motion carry the story, giving the platform a clear visual presence.',focus:'Bring together product detail and a confident pace. Transitions connect the interface moments, while composition keeps the attention on the product.',format:'Product promotion / Interface motion'},
 {id:'sag-ussd',title:'SAG USSD',category:'video',type:'Product walkthrough',cover:'assets/sag-ussd-poster.jpg',video:'assets/sag-ussd.mp4',intro:'A guided feature video showing how to access and use the Subandgain USSD service.',overview:'A practical walkthrough of the SAG USSD service. The video introduces the feature and guides viewers through using it.',focus:'Make the sequence easy to follow. Clear steps, readable information and purposeful pacing help turn an unfamiliar process into a straightforward task.',format:'Feature walkthrough / Motion graphics'},
 {id:'paiflo',title:'Paiflo',category:'branding',type:'Brand identity',cover:'https://mir-s3-cdn-cf.behance.net/projects/max_808_webp/af4bb5252721867.Y3JvcCwxMzgwLDEwODAsMjcwLDA.png',behance:'https://www.behance.net/gallery/252721867/Paiflo-Brand-Identity',intro:'A considered brand identity with clarity, credibility and an approachable character.',overview:'An identity project for Paiflo, exploring how a consistent visual language can give the brand a recognisable presence.',focus:'Balance a distinctive first impression with everyday usability. The identity brings typography, colour and graphic elements into a coherent visual direction.',format:'Brand identity / Visual direction'},
 {id:'bofal',title:'Bofal Business Hub',category:'branding',type:'Logo identity',cover:'https://mir-s3-cdn-cf.behance.net/projects/max_808_webp/6e7065252708315.Y3JvcCwxMjg4LDEwMDgsMTIxLDA.png',behance:'https://www.behance.net/gallery/252708315/Bofal-Business-Hub-Logo-Identity',intro:'A clear logo identity for a business-focused brand with room to grow.',overview:'A logo identity for Bofal Business Hub, centred on a confident and recognisable brand mark.',focus:'Keep the central idea clear and the mark adaptable. A restrained visual direction gives the identity a consistent presence across applications.',format:'Logo design / Identity'},
 {id:'hevm',title:'Hevm',category:'branding',type:'Brand identity',cover:'https://mir-s3-cdn-cf.behance.net/projects/max_808_webp/d0bc35229475243.Y3JvcCwyODEwLDIxOTgsMzQ3LDA.jpg',behance:'https://www.behance.net/gallery/229475243/Hevm-Branding',intro:'A distinctive brand system with bold visual cues and a confident digital presence.',overview:'A branding project for Hevm, bringing the identity together through a recognisable visual language.',focus:'Give the brand a clear character that can carry across different formats. Consistent graphic choices connect individual applications into one identity.',format:'Branding / Visual identity'},
 {id:'defiscan',title:'Defiscan',category:'branding',type:'Brand design',cover:'https://mir-s3-cdn-cf.behance.net/projects/max_808_webp/541e79229474823.Y3JvcCwxMTIxLDg3NiwxMzgsMA.jpg',behance:'https://www.behance.net/gallery/229474823/Defiscan-Brand-Design',intro:'A focused visual identity created around clarity and energy.',overview:'A brand design project for Defiscan, exploring a distinct and consistent visual presence.',focus:'Use a recognisable visual direction to connect the brand across its applications. The emphasis is on clear communication and a cohesive identity.',format:'Brand design / Visual identity'}
];
