// Add new projects here. Case-study copy is a first draft for Slimzy to review.
// No client quotes, performance figures or unverified project timelines are used.
const projects = [
 {id:'zidi',title:'Zidi AI Assistant',category:'video',type:'Product explainer',duration:'00:58',cover:'assets/zidi-ai-assistant-poster.jpg',video:'assets/zidi-ai-assistant.mp4',intro:'A product explainer introducing Zidi as a personal WhatsApp assistant for everyday utility transactions.',sections:[{title:'About the video.',copy:'The video presents Zidi as a familiar WhatsApp contact that helps users complete useful transactions through a simple conversation.'},{title:'What it shows.',copy:'Viewers see a utility purchase reach a successful transaction receipt, followed by a commission withdrawal request confirmed inside the same chat.'},{title:'Visual direction.',copy:'Clean typography, soft gradients and floating 3D accents keep the product approachable, while focused crops and steady pacing make every message easy to follow.'}]},
 {id:'axentra',title:'Axentra',category:'video',type:'Crypto platform promo',duration:'00:17',cover:'assets/axentra-poster.jpg',video:'assets/axentra.mp4',intro:'A short cinematic product reveal built around Axentra’s crypto trading dashboard.',sections:[{title:'About the video.',copy:'A focused 17-second promo designed to give the Axentra trading platform a confident, premium presence.'},{title:'What it shows.',copy:'The tilted dashboard reveals the BTC/USDT market, order book, price chart and buy-and-sell controls before a brief closing animation.'},{title:'Visual direction.',copy:'A dark environment, warm edge lighting and controlled camera movement create depth while keeping the trading interface as the main focus.'}]},
 {id:'sag-ussd',title:'SAG USSD',category:'video',type:'Feature walkthrough',duration:'00:43',cover:'assets/sag-ussd-poster.jpg',video:'assets/sag-ussd.mp4',intro:'A step-by-step video showing Subandgain users how to complete an airtime order with the SAG USSD service.',sections:[{title:'About the video.',copy:'A practical walkthrough created to make the SAG USSD airtime-purchase process quick and easy to understand.'},{title:'What it shows.',copy:'The video guides users through three steps: dial the SAG USSD code, enter the required USSD number and submit the USSD PIN to complete the order.'},{title:'Visual direction.',copy:'A phone mock-up, large step numbers and short instructions lead the sequence, supported by green brand shapes and clear high-contrast layouts.'}]},
 {id:'paiflo',title:'Paiflo',category:'branding',type:'Brand identity',cover:'https://mir-s3-cdn-cf.behance.net/projects/max_808_webp/af4bb5252721867.Y3JvcCwxMzgwLDEwODAsMjcwLDA.png',behance:'https://www.behance.net/gallery/252721867/Paiflo-Brand-Identity',intro:'A considered brand identity with clarity, credibility and an approachable character.',overview:'An identity project for Paiflo, exploring how a consistent visual language can give the brand a recognisable presence.',focus:'Balance a distinctive first impression with everyday usability. The identity brings typography, colour and graphic elements into a coherent visual direction.',format:'Brand identity / Visual direction'},
 {id:'bofal',title:'Bofal Business Hub',category:'branding',type:'Logo identity',cover:'https://mir-s3-cdn-cf.behance.net/projects/max_808_webp/6e7065252708315.Y3JvcCwxMjg4LDEwMDgsMTIxLDA.png',behance:'https://www.behance.net/gallery/252708315/Bofal-Business-Hub-Logo-Identity',intro:'A clear logo identity for a business-focused brand with room to grow.',overview:'A logo identity for Bofal Business Hub, centred on a confident and recognisable brand mark.',focus:'Keep the central idea clear and the mark adaptable. A restrained visual direction gives the identity a consistent presence across applications.',format:'Logo design / Identity'},
 {id:'hevm',title:'Hevm',category:'branding',type:'Brand identity',cover:'https://mir-s3-cdn-cf.behance.net/projects/max_808_webp/d0bc35229475243.Y3JvcCwyODEwLDIxOTgsMzQ3LDA.jpg',behance:'https://www.behance.net/gallery/229475243/Hevm-Branding',intro:'A distinctive brand system with bold visual cues and a confident digital presence.',overview:'A branding project for Hevm, bringing the identity together through a recognisable visual language.',focus:'Give the brand a clear character that can carry across different formats. Consistent graphic choices connect individual applications into one identity.',format:'Branding / Visual identity'},
 {id:'defiscan',title:'Defiscan',category:'branding',type:'Brand design',cover:'https://mir-s3-cdn-cf.behance.net/projects/max_808_webp/541e79229474823.Y3JvcCwxMTIxLDg3NiwxMzgsMA.jpg',behance:'https://www.behance.net/gallery/229474823/Defiscan-Brand-Design',intro:'A focused visual identity created around clarity and energy.',overview:'A brand design project for Defiscan, exploring a distinct and consistent visual presence.',focus:'Use a recognisable visual direction to connect the brand across its applications. The emphasis is on clear communication and a cohesive identity.',format:'Brand design / Visual identity'}
];
